### ISSUE TITLE
Has VAPOR3 been tested with Ubuntu 18.04 LTS ?

### ISSUE THREAD

**Issue by winash12** [NCAR/VAPOR#1135]
I have downloaded the latest VAPOR 3 binaries from the website and I am installing it and running it on Ubuntu 18.04 LTS.  I have gone through this video - [https://www.youtube.com/watch?v=gfj2PSd2rvE&list=LLw1vE3-Hn0fzlRGV5JIJWww&index=2&t=0s](url) and I am not getting to see the same controls that Scott does. So I am trying to open a file which is CF compliant and I am simply not getting to see the same layout or controls. I am now downloading the source code from github and building it from source as I do not know whether the 16.04 binaries will work on 18.04 LTS.

**Comment by shaomeng** [comment]
Hi @winash12 , to answer your question in short, no, we haven't tested Ubuntu 18.04. To elaborate, I suspect it still runs because you're able to open the application and see the controls. The layout different could be from 1) development of the program so controls are moved around, and 2) GUI difference between Ubuntu and CentOS. Have you tried to play with the controls you see, and see if the visualization functionalities are able to use?

**Comment by shaomeng** [comment]
Hi @winash12 , it makes sense to make use of the holiday time :) I've created an Ubuntu installer based on our latest development of VAPOR3, and I hope this one can get you busy over the holiday. It's available [here,](https://drive.google.com/file/d/16-uxQndx7YjCaTlXsBiDC-9RFEtvmLa1/view?usp=sharing) and please let me know if it works for you.
(We might have a crash issue on some platforms... Hope your platform isn't one of those affected... Let us know! )

**Comment by shaomeng** [comment]
Hi @winash12 , I've fixed the previously mentioned crashing problem, and created a new installer for you. Please feel free to give it a try: https://drive.google.com/file/d/1IPIbz2vmfbZokzFEqE0udMxOHaZ0y_Be/view?usp=sharing

**Comment by winash12** [comment]
@shaomeng Thanks for the download at all. No this does not load up at all. I start this with up and it just hangs with a small window and then there is no text message at all. It just hangs.

**Comment by winash12** [comment]
OK I tried that as root user and now as myself I get this message - "InitializeGL Failure OpenGL version "3.0 Mesa 18.0.5"  is too low and not supported. " An error has occurred Failure to initialize Initializer

**Comment by winash12** [comment]
Does VAPOR3 come bundled with all the dependencies ? For e.g. I know it needs Qt from VAPOR2. But I did not have to point out the location of Qt5 to VAPOR3 - so how does it find out the dependency ? I have built VAPOR2 from scratch on Ubuntu 16.04 by patiently compiling all the dependencies one by one. But in this case I am a bit confused on how the dependencies are located.

**Comment by shaomeng** [comment]
Hi @winash12 , you really provide a lot of information! Let me get to them one by one. 
- You really don't need to install it as root user. You just need to make that `.sh` file executable and run it, choose a local directory to install, and you're good to go! 
- Your OpenGL seems to have problems. It's using Mesa, the software OpenGL implementation. You should install the Intel graphics driver so that your system uses your Intel graphics card for OpenGL. (I suspect you can simply install Intel graphics driver from within Ubuntu, and then remove the Mesa library. Is Ubuntu 18.04 your system? )
- VAPOR bundles all the dependencies. The `.sh` installer is a self extraction bundle with all the dependencies as well as VAPOR. Once installed, VAPOR should run within that local environment without looking for anything elsewhere.

**Comment by winash12** [comment]
@shaomeng Thanks for your prompt response. Yes I am on Ubuntu 18.04 LTS. Unfortunately I cannot remove OpenGL Mesa library. It is used by other softwares. I am not sure what Intel graphics card is being used by my Ubuntu - [https://askubuntu.com/questions/1056862/how-to-install-intel-graphics-drivers-on-ubuntu-18-04](url) and[https://askubuntu.com/questions/1076950/intel-graphics-drivers-update](url). If you have tested this on Ubuntu 18.04 can you tell me how to point to the Intel graphics driver ?

**Comment by winash12** [comment]
OK on 18.04 when I go to Additional Drivers  I see no options whatsoever and it says No additional drivers are available. No proprietary drivers are in use.

**Comment by shaomeng** [comment]
@winash12 check this out: https://unix.stackexchange.com/questions/963/how-to-verify-if-hardware-acceleration-is-enabled .

I was able to verify my machine to be `Yes` on `direct rendering`.

**Comment by winash12** [comment]
@shaomeng I was also able to verify my machine to be "Yes" on direct rendering. I have asked this question on - https://askubuntu.com/questions/1104385/i-need-to-point-to-intel-graphics-card-drivers-on-ubuntu-18-04-lts-how-can-i-do

**Comment by shaomeng** [comment]
Hi @winash12 , I'm confused right now too, given that Intel and Mesa do seem to go hand in hand... I guess I'll have refer this question to @StasJ , who is the OpenGL guru here in the group, and thank you very much for testing out VAPOR and report the issues. 

Stas, the OpenGL output by Winash12 has the following strings
```
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.50
...
OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
```
and yet VAPOR reports 

`InitializeGL Failure OpenGL version "3.0 Mesa 18.0.5" is too low and not supported.`  Is it some expected behavior?

**Comment by winash12** [comment]
@shaomeng If you can list out the dependencies that VAPOR3 needs on  a URL  somewhere I would like to build it from scratch on Ubuntu 18.04.

**Comment by winash12** [comment]
@shaomeng It looks like these dependencies are for VAPOR2.x. Do you not support Python3 and Qt5 now ? Regarding OpenGL I think unless you test it on 18.04 and reproduce this problem let us just wait..

**Comment by shaomeng** [comment]
Hi @winash12 , our team member @StasJ has created an installer that does NOT perform the OpenGL version check, and would like for you to try if it performs meaningful visualizations. Specifically, it'd be good to try the `Fixed step size casting` volume rendering, see if it works. 
The installer is here:
https://drive.google.com/file/d/1IPIbz2vmfbZokzFEqE0udMxOHaZ0y_Be/view?usp=sharing

Let us know what you find out!

**Comment by winash12** [comment]
It just crashes. 
/lib/x86_64-linux-gn/libc.so.6(__libc_start_main+0xe7)
Error : BadDrawable (invalid Pixmap or Window parameter) 9

Major opcode : 62 (X_copyarea)
Resource id : 0x0

Unless you get this running from a Ubuntu 18.04 instance from your end... I fear I will be just trying and trying...

**Comment by StasJ** [comment]
Hi @winash12, we were able to reproduce your issue on a local machine and we are working on getting it fixed. Thank you for help and patience. We will let you know once it is fixed.

**Comment by clyne** [comment]
Good deal! @shaomeng can you generate another installer for @winash12 to try?

**Comment by shaomeng** [comment]
Hi @winash12 , can you try our latest installer: 
https://drive.google.com/file/d/1IPIbz2vmfbZokzFEqE0udMxOHaZ0y_Be/view?usp=sharing

**Comment by winash12** [comment]
@shaomeng @StasJ @clyne That works ! I am able to load the COSMO weather model .nc file. But I will need to look at the documentation and maybe some offline guidance on how to view data because all I can see right now is a 3D cube.
