### ISSUE TITLE
TFWidget: different histogram between VAPOR 2 and 3

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1158]
To reproduce:

1. Open VAPOR2 and VAPOR3, load ROMS data: `/little_glade/data/Source/ROMS/jsmall/b.n20.B1850CN.f09_g16.ccs1.02.roms.ha.0098-01.nc`
2. Create a DVR renderer, update the histogram.
3. The histogram and bounds look different between VAPOR 2 and 3, see attached. 

(I suspect this bug has something to do with issue #1154 )

VAPOR 2:
![screenshot 2019-01-02 17 27 00](https://user-images.githubusercontent.com/814885/50619046-1920e880-0eb4-11e9-8040-28be88017b3d.png)

VAPOR 3:
![screenshot 2019-01-02 17 27 08](https://user-images.githubusercontent.com/814885/50619048-19b97f00-0eb4-11e9-9918-f894b24e0f97.png)

**Comment by clyne** [comment]
In vapor2 every bin in the histogram was biased, as needed, to ensure a bar was always drawn for each bin. This is not done in VAPOR3. One could argue that the VAPOR3 behavior is the correct one. I'm inclined to reject this bug unless there is more to the differences than what i just described.

**Comment by shaomeng** [comment]
@clyne does the bin bias explain the difference in extents? In VAPOR2, it shows (-0.027, 0.802). In VAPOR 3, it shows (0, 0.808).

**Comment by sgpearse** [comment]
I'm not too suprised that the range is different between v2 and v3, since we're not sampling every data point in v3.

**Comment by shaomeng** [comment]
@sgpearse Doesn't the cyan color in the VAPOR 3 histogram indicate an accurate histogram, as the screenshot shows?

**Comment by sgpearse** [comment]
@shaomeng The grey color indicates that the histogram's minimum and maximum bounds have been changed, and it's not currently up to date.  It turns cyan after the Update button has recalculated it.

**Comment by shaomeng** [comment]
@sgpearse Gotcha. Then the next question is, how can I adjust the TF so that I can visualization the negative values in my data set?

**Comment by sgpearse** [comment]
Good question.  I believe that you actually don't need to in this case, because Vapor2's histogram calculation actually appears to be incorrect.

The following screenshot uses a boolean histogram scale.  Instead of a probability distribution, any value will register along the entire Y axis of the histogram.  Note that there are no values below 0.

![screen shot 2019-01-03 at 10 31 20 am](https://user-images.githubusercontent.com/9522770/50652339-7ca62700-0f43-11e9-91e3-0ffaa12c47cf.png)

If you run _ncdump -v AKv /little_glade/data/Source/ROMS/jsmall/b.n20.B1850CN.f09_g16.ccs1.02.roms.ha.0098-01.nc |less_ and search for -0, there will be no results, indicating that there are no negative values for that variable.

Try it with the variable v: _ncdump -v v ~/little_glade/data/Source/ROMS/jsmall/b.n20.B1850CN.f09_g16.ccs1.02.roms.ha.0098-01.nc |less_.  This produces many results when we search for -0.

I'm not sure why Vapor2 is finding negative values for AKv, but it seems to be in error.

**Comment by clyne** [comment]
Can we reject this?

**Comment by shaomeng** [comment]
Looks about right, let's reject it!
