### ISSUE TITLE
Orthographic Geotiff Bug

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1244]
The orthographic geotiffs seem to have trouble with CAM data.

To reproduce:
1) Import the NetCDF-CF file /little_glade/data/Source/CAM/Gaussian/b30.030a.cam2.h0.TS.1870-01_cat_1999-12.nc
2) In the Navigation, Viewpoint tab, enable the Map Orthographic projection
3) Create a TwoDData renderer and enable it
4) Capture a single TIFF image of the TwoDData Renderer
5) Create an image renderer and point it to your new GeoTiff.  I believe it should align with the domain, but it does not seem to.

![screen shot 2019-01-08 at 1 45 50 pm](https://user-images.githubusercontent.com/9522770/50857848-1149c400-134c-11e9-8c9e-68c65ff800c2.png)

**Comment by StasJ** [comment]
The issue is you cannot save an image with geo-referenced coordinates larger than the earth. Should we try and fix this? @clyne 

Here is the same dataset with a geo-referenced image of South America taken with the issue steps.
<img width="714" alt="screen shot 2019-01-09 at 1 52 31 pm" src="https://user-images.githubusercontent.com/2772687/50927728-d6ac5e00-1415-11e9-8e70-ed4c996759a4.png">
