### ISSUE TITLE
VAPOR fails to load data set: 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1365]
VAPOR fails to load VDC data set upon starting. The error message shows: Failed to get camera parameters. 

Platform: cisl-vapor.
Command: `./bin/vapor /little_glade/shaomeng/synthetic/checker.nc`

**Comment by StasJ** [comment]
I found the cause of the bug but I am not sure how to fix it because I am unfamiliar with the code. Also the logic it follows doesn't really make sense as I describe below, so could you please take a look at it @clyne?

In commit e2d22118, you modified `DataMgr::_hasHorizontalXForm`

The original code checked if a an axis had a corresponding lon/lat unit? The new code adds additional check which doesn't really make sense: The code is checking if `(axis=0 AND (IsLon OR isLatORLon)) OR (axis=1 AND (IsLat OR isLatORLon))`
