### ISSUE TITLE
Multiple Dataset: streching factor or Barb renderer messed up

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1390]
To reproduce: 
1. Open VAPOR, Import CF data: `/little_glade/shaomeng/nc-vapor3/cm1.nc`
2. Create a Slice renderer, enable it. Notice the bounding box is correct.
3. Load VDC format of Duku. Notice that the bounding box changes.
4. Create a slice renderer. Notice that the rendering is on only half of the bounding box:
![screenshot from 2019-01-25 17-01-15](https://user-images.githubusercontent.com/814885/51779195-11bfba00-20c3-11e9-8188-786512e81828.png)
5. Delete all existing renderer. Create a new slice renderer with data set `cm1`. Now you can render nothing on the screen.
6. Change the sliders in the geometry tab, still nothing got renderer.

**Comment by sgpearse** [comment]
This turns out to be a scaling issue.  Leigh's model is on the scale of hundreds of meters, and is practically an LES.  The DUKU simulation is between synoptic and mesoscale, which have domains in the realm of thousands of kilometers.  Leigh's dataset, is getting rendered, but it's just so small compared to DUKU that you can't see it.

<img width="1137" alt="screen shot 2019-01-28 at 2 03 43 pm" src="https://user-images.githubusercontent.com/9522770/51866321-f7c1e980-2305-11e9-8b74-a2dca98626a5.png">
<img width="1137" alt="screen shot 2019-01-28 at 2 03 05 pm" src="https://user-images.githubusercontent.com/9522770/51866328-f98bad00-2305-11e9-825c-2f822a403e82.png">
<img width="1138" alt="screen shot 2019-01-28 at 1 58 44 pm" src="https://user-images.githubusercontent.com/9522770/51866329-fa244380-2305-11e9-9f2c-c7d20d79374f.png">
<img width="1136" alt="screen shot 2019-01-28 at 1 58 27 pm" src="https://user-images.githubusercontent.com/9522770/51866330-fa244380-2305-11e9-9c59-4b3f842abc7c.png">
