### ISSUE TITLE
Seemingly broken IsoSurface on MacOS

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#1627]
The isosurface renderer on macos seems broken, as the screenshot shows.

To reproduce: 
1. Open VAPOR, load data `/little_glade/shaomeng/cm1.nc` (`/glade/p/cisl/vast/vapor/Bugs/cm1.nc`)
2. Create an isosurface renderer, change the isovalue to be 1.331, and enable this renderer.
3. The rendering result seems broken. It looks correct on cisl-vapor though.

Platform: macos+intel

![Screenshot 2019-06-05 10 43 13](https://user-images.githubusercontent.com/814885/58974219-29990000-877f-11e9-8fb9-6fad43787194.png)

**Comment by StasJ** [comment]
This is some sort of driver bug. I'm at my wits end with these things. Here is what is happening:

```
int FindInitialCell(...)
{
    return 0; // Do nothing
    // Finds the initial cell
}

void main()
{
    // If I return here, the resulting image is correct
    intersections = FindInitialCell(...);
    // If I return here, the resulting image is corrupted
}
```

I have tried other datasets of higher resolution on my mac without this issue. It appears to be somehow localized to this dataset and only at the highest resolution.

**Comment by StasJ** [comment]
It appears this happens when you run out of GPU RAM

**Comment by StasJ** [comment]
An additional note relating to my original comment about the driver bug: In GLSL, if a variable is not used to compute the final result, it is optimized out. If the optimizer removes enough texture variables so that the data fits within RAM, there will be no glitches. For some reason, the optimizer is able to optimize out the textures if I return before calling the function `FindInitialCell`, but not if said function immediately returns 0.

**Comment by shaomeng** [comment]
We probably really shouldn't use OpenGL for renderers that are more
complicated than Contour Renderer...
