### ISSUE TITLE
Flow: Wrong number of seeds

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#1848]
I cannot seem to render the correct number of seeds that request in the GUI.

Load the attached session file after removing the .txt extension (enforced by GitHub).

[cannotSeeSeeds.vs3.txt](https://github.com/NCAR/VAPOR/files/3581447/cannotSeeSeeds.vs3.txt)

Load the following into the attached session:
Dataset: DUKU
/glade/p/cisl/vast/vapor/data/VDC/vapor-3.0.0/WRF/DUKU/DUKU-3.0.0.nc

Or do the following:
1) Load the previously mentioned dataset
2) Create and enable a Flow renderer
3) Set the Seed Generation Mode to "From a Rake Randomly"
4) Increase the number of seeds to 10
5) Increase the ZMin extent to roughly 10,000 (this excludes the terrain from the region)

**Comment by shaomeng** [comment]
I think either of these two cases happened:
1) a seed is still generated in the missing value regions
2) a seed is not in a missing value regions, but is advected there in its first few steps, thus not shown.

That is because you get different number of lines every time you run the program. Sometimes it's less than 10, while some other times it's at 10.

**Comment by shaomeng** [comment]
Update: 
Inserting print statements verify that the correct number of seeds are generated. They aren't displayed because of missing values.
