### ISSUE TITLE
GeometryWidget: keeps copies of three pointers? 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#200]
Could @clyne clarify if the following practice is encouraged? 
Specifically, the widget keeps copies of three pointers as private members and uses them repeatedly across the class. 

https://github.com/NCAR/VAPOR/blob/793724edae81b81855fed9243f14403551ba54ba/apps/vaporgui/GeometryWidget.h#L55-L58

**Comment by clyne** [comment]
This is the problem I spoke of yesterday. The ParamsMgr is the only one of the 3 pointers that is not volatile. However, we've been getting lucky because the Update() method has been refreshing all the pointers ahead of any method that might access them. We should *probably* refactor the "composite widgets" (e.g. Geometry, Appearance, etc.) so that their more robust. But since we've not seen any problems i'm changing the priority to medium

**Comment by shaomeng** [comment]
I don't think the pointers are refreshed before being accessed.
Take a look at `GeometryWidget::setRange()` slot:
https://github.com/NCAR/VAPOR/blob/f07d2f5ab5df2e3d7e777805323d2278457ec03b/apps/vaporgui/GeometryWidget.cpp#L307-L323

This slot is triggered whenever the slider is moved. The `Update()` method that refreshes all the pointers are called AFTER `setRange()` is called, not before.

Or am I missing something?

**Comment by clyne** [comment]
No longer applicable after GUI refactoring
