### ISSUE TITLE
Dataset coordinates not recognized

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2071]
The dataset below has variables xPos, yPos, and zPos that are supposed to comprise a coordinate variable yet Vapor does not read them as such.

`cisl-vapor:/little_glade/bugs/2071/`

**Comment by clyne** [comment]
This file is not CF compliant, at least not wrt the use of xPos, yPos, and zPos as coordinate variables. So there is no way for VAPOR (or any other tool) to infer that xPos, etc. are indeed coordinate variables. The way this file is structured xIndex, yIndex, and zIndex are assumed to be the only coordinate variables in the data set. 

Changing the file so that xPos, etc. are recognized as coordinate variables under the CF conventions should be relatively straightforward, and is described in the CF specification. However, xPos, yPos, and zPos are each 3-D variables. Currently, vapor only supports curvilinear grids where the X and Y coordinate variables are 2D, and the Z coordinate variable may be either 1D or 3D.

**Comment by phawbeck** [comment]
After changing the coordinates of the 2D and 3D variables to new coordinate variables (X, Y, and Z) that are 2D, 2D, and 3D, respectively, the problem appears to be resolved. Thank you very much for the information!

**Comment by clyne** [comment]
Outstanding! I love it when stuff works!


> On Jan 10, 2020, at 12:45 PM, Patrick Hawbecker <notifications@github.com> wrote:
> 
> After changing the coordinates of the 2D and 3D variables to new coordinate variables (X, Y, and Z) that are 2D, 2D, and 3D, respectively, the problem appears to be resolved. Thank you very much for the information!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
