### ISSUE TITLE
ISOSurface color suspicious 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2082]
In the attached screenshot, the same variable is selected for isosurface and color mapping. There's only one isosurface enabled. Shouldn't it display a constant color in this case? VAPOR shows a quite colorful rendering though.

Data: `/little_glade/data/VDC/vapor-3.2.0.alpha/CAM/FiniteVolume/cam_fv`
To reproduce: 
1. load the data set above, create an Isosurface renderer.
2. Select both data variable and color mapping variable to be CLOUD
3. Increase the data fidelity to the highest level
3. Enable color mapping by variable. 

![iso](https://user-images.githubusercontent.com/814885/72195579-3e520c00-33d0-11ea-824a-5ba87dcbeb6e.png)

**Comment by StasJ** [comment]
I followed the instructions and got the following:

![s](https://user-images.githubusercontent.com/2772687/72471846-a4f47280-37a0-11ea-826a-662596ec049f.png)

**Comment by shaomeng** [comment]
> I followed the instructions and got the following:
> 
> ![s](https://user-images.githubusercontent.com/2772687/72471846-a4f47280-37a0-11ea-826a-662596ec049f.png)

Did you try to use a higher fidelity level, as the screenshot shows? 
(I'll update the description)

**Comment by StasJ** [comment]
That was not part of the reproduction instructions. I went ahead and increased the fidelity to the maximum and I still cannot reproduce your image because you are doing other things to exacerbate the problem such as disabling lighting. The color discrepancy you see is because this is a sampling based renderer and therefore the calculations are not continuous and perfect. In 99% of real use cases, the current solution would work just fine. For the last 1%, you can just increase the sampling rate to fix the problem, which it does here. This dataset also has high frequency data which makes slight error in the sampling more apparent.

Coloring an isosurface by the same variable is not a real use case, but since it has been brought up multiple times and we’ve decided it is a must fix, I will go ahead and make sure the samples are perfectly on the isosurface surface.

**Comment by shaomeng** [comment]
Thanks Stas. It's up to you to decide if this is a real bug and if it is,
how easy/hard to fix. But in any case, I don't know where is this coming
from:
"you are doing other things to exacerbate the problem such as disabling
lighting."
