### ISSUE TITLE
Barb Crash if assign a renderer name

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#21]
To reproduce:
1. Load KatrniaMaster.nc
2. Click "new" button to create a Barb renderer. Give the renderer a name, say "AAA."
3. Click OK. Vapor crashes.

Machine: 
cisl-vapor

**Comment by shaomeng** [comment]
The same is true for Contour renderer.

**Comment by StasJ** [comment]
The application crashes when the renderer name starts with a whitespace character. At some point, when retrieving render params, it searches for the whitespace-trimmed renderer name which is stored as the original string containing whitespace. Vapor then crashes when it fails to find the renderer.

This problem occurs so often because the text area for inputting a name has a space in it by default, and when you click in it to add a name, it appends your name to the existing space which appears to be just padding to the user without further inspection.

**Comment by StasJ** [comment]
It does additional processing with regards to spaces. For example if you enter the name "ab cd", ParamsMgr has the renderer stored as "ab cd", however when GetActiveParams is called from updateTab, it tries to search for "ab"
