### ISSUE TITLE
Volume Renderer: Load builtin colormap broken

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2152]
To reproduce:

1) Load any dataset
2) Create a volume renderer and change the color-mapped variable to be different than the primary variable
3) In the Appearance tab, check "Color by second variable"
4) Load a built-in colormap.  It will not load.

**Comment by StasJ** [comment]
This is intentional. That menu item is linked to the main transfer function. When you enable colormapping by a second variable, there are now two transfer functions. To operate on the second transfer function, you right click on it which gives you access to the same commands. As an example, there is a `Save Transfer Function` menu button. If you pressed that, which of the two transfer function would it save? That is why I had the top right menu affect the main variable transfer function only.

![s](https://user-images.githubusercontent.com/2772687/73094862-b293b180-3e9e-11ea-82b1-72f0858df36f.png)
