### ISSUE TITLE
Flow: Streamline data file can only be written once

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2418]
I seem to only be able to write the flow streamline .csv once.

To reproduce on OSX:
1. Delete ~/VaporFlow.txt
2. Create a default flow renderer, and write VaporFlow.txt with the first variable in the list (P in DUKU's case)
3. Note the time of day that the file was written
4. Wait a minute and try to write the file again.  The timestamp does not update

**Comment by shaomeng** [comment]
I confirm that this is caused by paint event triggered only once when clicking on "write to file" button in a row. If a user does something else, e.g., rotating the scene, then you can trigger another paint event when clicking the button. Maybe someone who's more familiar with triggering paint events can take a look at this issue?
