### ISSUE TITLE
OSPRAY crash on cisl-vapor

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2420]
There's an Ospray crash bug as described [here](https://github.com/NCAR/VAPOR/pull/2401#issuecomment-717485801). 

Note: this could well be an issue on the particular test machine (cisl-vapor).

**Comment by StasJ** [comment]
OSPRay loads its libraries dynamically at runtime therefore the build system has no way of knowing what libraries it needs. Since on linux we use the hard library paths for running development builds it will not work. You can add linker paths to the runtime search paths with CMake but it is already configured to do this. It seems that it works on some systems (casper) but not on cisl-vapor. For the installer, the linker search path is manually set with the launchers so it is not an issue. To address the issue on cisl-vapor you can add ospray/lib to your LD_LIBRARY_PATH

**Comment by clyne** [comment]
Need to verify after #2453 is resolved.
