### ISSUE TITLE
Annotation Tab uses different coordinate systems for different options

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2473]
In the Annotation tab, we are using user-coordinates for specifying axis annotations, and a unit square (0:1 on X Y and Z) for placing the RGB arrows.  We should probably use either one or the other.

**Comment by clyne** [comment]
This may be a duplicate.

**Comment by clyne** [comment]
This is not fixed. However, I'm not sure I agree that we should change the current behavior. The RGB arrows are in 2D image coordinates, and it makes sense to specify them in NDC coordinates (0.0 - 1.0). The tick marks are 3D and most of our 3D coordinates (e.g. Geometry) are specified in user coordinates. I'd be inclined to mark this as rejected rather than fixed.
