### ISSUE TITLE
Flow crashes on 2D dataset

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2477]
To reproduce:

1) Import the wrf file /glade/p/cisl/vast/vapor/data/Source/WRF/2D/wrf.nc
2) Create a Flow renderer, and use U10 and V10 for the X and Y field components
3) Enable the renderer and Vapor will crash

Test machine: Casper

**Comment by shaomeng** [comment]
Cannot reproduce on cisl-vapor. @sgpearse is it trivial to build VAPOR on Casper? I will need to build there and debug there.

**Comment by shaomeng** [comment]
Upon investigation, this bug seems to stem from the "color mapping variable" widget fails to register the default value. In this particular test case, 
1) upon creation of a flow renderer, the "color mapping variable" field has a `CLDFRA_HGH` entry, but the params class returns an empty string when querying `params->GetColorMapVariableName()`;
2) if a user selects that variable from the menu, then the query returns the correct value.

**Comment by StasJ** [comment]
> Upon investigation, this bug seems to stem from the "color mapping variable" widget fails to register the default value. In this particular test case,
> 
> 1. upon creation of a flow renderer, the "color mapping variable" field has a `CLDFRA_HGH` entry, but the params class returns an empty string when querying `params->GetColorMapVariableName()`;
> 2. if a user selects that variable from the menu, then the query returns the correct value.

It is not the job of the widget to register a default value, but rather the params class. In this case, the variable selector widget is configured not to provide the `<none>` option so this is an invalid state and the behavior is undefined. I added a PR (#2500) that will cause it to show `<none>` even if it is not supposed to have a `<none>` option when the variable is empty.
