### ISSUE TITLE
Flow: List of seeds not working?

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2543]
Produced on Casper.

The session /glade/u/home/pearse/brokenListOfSeeds.vs3 uses a "List of seeds" file in its flow streamline renderer.  

The file being used is /glade/u/home/pearse/listOfSeeds.txt, and defines one seed at 0,0,3,0 (x,y,z,time).  This streamline should only be drawn at the first timestep, but it persists for all 9.

**Comment by shaomeng** [comment]
@sgpearse The current behavior of the software is that when in "Streamline" mode, the seed/particle information is ignored, and the software uses velocities from whatever the current time step is to perform "streamline" integration. That is because, almost by definition, streamlines imply that time is constant. 

I guess my question for you is:
1) is the behavior described above understandable and reasonable?
2) if it is reasonable, does your test show behaviors otherwise?

**Comment by sgpearse** [comment]
Hmm.  I understand what you mean, and I'm not certain what the right thing to do is.  

On one hand, having a consistent format for the list-of-seeds file would be less complex for the user.  Using different formats means there's more code for us to maintain, and more things for the user to remember when writing their file.

On the other hand, do users ever want to change streamline seed locations across time?  Perhaps...

One thought is that moving domains have changing coordinates.  If a user is defining streamlines in Katrina, will the X,Y,Z,T values be valid after the moving domain has shifted beyond the initial time step?

**Comment by clyne** [comment]
Agreed that we would simply remove time coordinate from the list of seeds file and allow the GUI to control the time.
