### ISSUE TITLE
Vapor prefs being overridden

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2681]
1. Open a session
2. Check that the ram cache limit is 8000. If not, delete vapor prefs and create a new session, save it and repeat.
3. Change the ram cache limit to 12000

Notice the vapor prefs file now has a limit of 12000

4. New session
4. Import a dataset
5. Close vapor
6. Open the original session

Notice the vapor prefs file now has a limit of 8000

**Comment by clyne** [comment]
The vapor prefs file and the session file both contain the cache size (as well as other parameters), which makes because the session file contains the entire state of the application. We need to ensure that the prefs settings are loaded *after* the session file. It looks like the constructor for SettingsParams is reading the prefs file. This is probably not ideal because it violates having "no fail"constructors, plus it doesn't provide a way to ensure prefs take precedence over whatever is in the session file. I think we need an explicit "load prefs" method for SettingParams that is called whenever a session file is loaded.
