### ISSUE TITLE
Should 2D barb mode have a selection for Z field? 

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#2687]
I'm confused and don't know if this is intended, but it I thought 2D barb should not have anything to do with a Z field? 

![Screenshot from 2021-04-01 19-31-22](https://user-images.githubusercontent.com/814885/113370453-22ae8a80-9321-11eb-83bf-fb5fb4f45818.png)

**Comment by sgpearse** [comment]
It should.  It's not a common use case though, so we default the Z field to <none>.

Many WRF datasets contain the 2D variables U10 and V10, which are the X/Y vectors, 10 meters above ground.  If a dataset contained W10, we'd want to support that Z vector by tipping the barbs upwards and downwards.  

This is not the case for flow though, because we cannot advect outside of the plane.
