### ISSUE TITLE
vdccreate/raw2vdc gives wrong results with small/test datasets

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#2926]
VDC gives incorrect results with very small test datasets.  Summarized from #2920. 

To reproduce:

1) Download the attached files
2) Run the following commands

`vdccreate -vars3d temp -dimension 4X4X4 temp.vdc`
`raw2vdc -varname temp temp.vdc temp_binary.bin`

3) Vapor will load the dataset, but no domain will be shown

[Archive.zip](https://github.com/NCAR/VAPOR/files/7663588/Archive.zip)

**Comment by clyne** [comment]
This is not a problem with the VDC. The data are correctly encoded and can be reconstructed faithfully. This can be verified by running

`vdc2raw -var temp temp.vdc temp_reconstructed 
`
and inspecting the original and reconstructed data (e.g. with od -f)

The problem is that with VDC data the GUI uses the lowest resolution data to compute
the domain size. For a 4x4x4 grid, the coarsest resolution is 1x1x1, hence the domain volume collapses to a point, which the GUI is apparently not handling correctly. Or maybe it is handling it correctly and the only thing being drawn is a point (not a box). Perhaps a warning should be issued by the GUI, or a glyph should be drawn in this case?

@sgpearse , @StasJ thoughts?

**Comment by sgpearse** [comment]
Closing, since this is an edge case that won't be seen in any practical circumstance.
