### ISSUE TITLE
Replacing data used by flow renderer causes crash

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2935]
Open a release build of Vapor on Casper

1. Open VDC `Bugs/2935/MFR1`
2. Create/enable a flow renderer with appropriate vars
3. Open VDC `Bugs/2935/MFR` and replace existing dataset

Vapor will crash (usually).

Somewhat nondeterministic. Using a 3.5 installer on Casper seems to be most consistent but a source release build will crash eventually too.
Other renderers appear to work.

**Comment by shaomeng** [comment]
Well, it seems this crash is caused by "FlowRenderer" not aware of a new "DataMgr" that is created by a "replacing existing data" event. 

Could someone ( @StasJ @clyne @sgpearse ) help specify how should a user of a grid deal with the following situation:
1. A user (`VaporField` in this case) requests a grid from the DataMgr and has it locked.
2. The user intends to unlock this grid via the DataMgr and then delete the grid after finishing using it.
3. DataMgr is changed before the user had a chance to unlock the grid. I.e., the user now holds an invalid pointer pointing to the old DataMgr.

**Comment by clyne** [comment]
@StasJ , I think you are going to have to look at this. The DataMgr is being destroyed *before* the renderers. I think you introduced some logic to delay the destruction of active renderers in the Visualizer class (see _renderersToDestroy). I'm sure there was a good reason for doing this, but the Renderer destructor should not be called before the DataMgr destructor because the Renderers are allowed to shallow copy a pointer to the DataMgr.

**Comment by StasJ** [comment]
@clyne The DataMgr was always destroyed before the renderers (see `ControlExecutive.cpp:460`). I delayed the destruction of the renderers further since they need to access their OpenGL context to cleanup GPU RAM which is only available during paintGL (without hacks).

In any event, my understanding is that Grid is not guaranteed to remain valid for the lifetime of the renderer, only the lifetime of a single render call. For example, simply changing the timestep would, although not physically, logically make the saved grid pointer invalid. Even if there were some reason to hold on to a Grid pointer between draw calls, there shouldn't be any reason for the renderer to need to utilize that grid in the destructor.

**Comment by clyne** [comment]
Hmm. I guess i have to agree that it would simplify things and make the code more robust if the DataMgr wasn't shallow copied from the constructor. I.e it would probably be better to pass the DataMgr as an argument to DataMgr::PaintGL(). This would help avoid situations like this in the future.

@shaomeng this would only present a problem for the flow FlowRenderer, which accesses the DataMgr in its class destructor to unlock locked memory. Is there a reason that the FlowRender can't unlock variables at the end of the paint method? This would make its behavior consistent with the other renderers and fix this problem?

**Comment by shaomeng** [comment]
FlowRender implements a simple cache thing that provides a strong guarantee that these 3 (in steady case) or 6 (in unsteady case) grids are always available. This guarantee is implemented by locking a grid after acquiring it. 

But since locking a grid doesn't guarantee that the grid is always there, I don't think the simple cache in FlowRenderer is necessary at this time. If you all agree, I can go ahead and remove the cache thing from FlowRenderer.

**Comment by clyne** [comment]
@shaomeng the DataMgr lock will guarantee that the grid memory is valid for the lifetime of the DataMgr. But the DataMgr is not guaranteed to live from one paint call to the next. Ultimately, the DataMgr should probably be passed in as an argument to Renderer::paintGL. That would clarify things, but you will still not to unlock the grids before returning from paintGL; you don't need to remove your caching code, but you need to make sure everything is freed before paintGL returns.

Thanks!

**Comment by shaomeng** [comment]
Ok, I'll go ahead and implement this fix then!
