### ISSUE TITLE
SliceGridAlongPlane returns incorrect grid

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2969]
1. Slice a 3D grid using SliceGridAlongPlane

Notice that the all Z values for the Grid's coordinates are always 0
Rendering the grid with the wireframe renderer also reveals that the grid is incorrect.

**Comment by sgpearse** [comment]
@clyne and @stasj - I believe the problem is that the RegularGrid class cannot currently store the coordinates of 2D grids **that are not axis aligned**.

You can see the Slice's constructor [here](https://github.com/NCAR/VAPOR/blob/eb5f3a40783b958293e9aec5eca2141ac83bdc31/lib/vdc/SliceGridAlongPlane.cpp#L239), where dimensionality and coordinate extents are defined.  The dimensions are [ sampleSize x sampleSize x 1 ] followed by the Box extents.  I believe the Grid class currently assigns a value of 0 to grids that have a dimension equal to size 1.

**Comment by clyne** [comment]
@sgpearse prior to the merge of PR #2943 that was certain the case: only axis-aligned 2D grids were supported. It now *should* be possible to describe a plane that is not axis-aligned. However, it is possible that there is a bug. A couple of thoughts on how to move forward:

1. Define an arbitrary 2D coordinate system (e.g. unit normalized) in the RegularGrid, and transform the 3D world coordinates into the 2D used by the Grid. 
2. Try and run down and fix whatever problem there may be in the Grid class with 3D coordinates and a 2D grid. I have limited cycles to help out on this, but if you can provide an example that demonstrates the problem I can take a look at it. Ultimately, we should add a test case to our test suite.

**Comment by sgpearse** [comment]
@clyne - Got it.  I'll update soon with findings and possibly further questions.

**Comment by sgpearse** [comment]
@clyne - 

**Suggestion 1** 
I'm a little unclear.  Are you suggesting that the SliceRenderer and ContourRenderer should deduce the user coordinates of grid cells, after receiving the grid from SliceGridAlongPlane()?

**Suggestion 2** 
Update - The problem is that the RegularGrid class has a notion of _delta, which is a VAPoR::CoordType that describes the increment between vertices along the grid's xyz axes.   It is used to determine grid point locations in user-space.

Currently, we can query a RegularGrid's index [0,0,0] and expect that [0,0,1] will have a larger Z coordinate.  This does not work with rotated slices since the Z dimension is always of size 1 (does that make sense?).  The Slice's Z coordinate will depend on the X and Y indices being queried, **along with the rotation parameters** of the sliced grid.  _delta must account for rotation to give correct user coordinates.

I've started going down this path with the RegularGrid by adding the rotation parameters.  I'm giving them default so previous instantiations of RegularGrid should continue working.  But there are 10 functions in the RegularGrid class that utilize _delta, and I'm concerned about regressions.

**Option 3**
Another option is to create an UnstructuredGrid2D with explicitly defined grid points.  The constructor is a bit of a beast  so I'm shying away from this route until I can get some advice.

**Comment by clyne** [comment]
> @clyne -
> 
> **Suggestion 1** I'm a little unclear. Are you suggesting that the SliceRenderer and ContourRenderer should deduce the user coordinates of grid cells, after receiving the grid from SliceGridAlongPlane()?

I thought that was exactly what you were doing earlier when the slice was simply a raw array. In any event, that's probably not what you want to be doing, so I'd say forget this option.

> 
> **Suggestion 2** Update - The problem is that the RegularGrid class has a notion of _delta, which is a VAPoR::CoordType that describes the increment between vertices along the grid's xyz axes. It is used to determine grid point locations in user-space.
> 
> Currently, we can query a RegularGrid's index [0,0,0] and expect that [0,0,1] will have a larger Z coordinate. This does not work with rotated slices since the Z dimension is always of size 1 (does that make sense?). The Slice's Z coordinate will depend on the X and Y indices being queried, **along with the rotation parameters** of the sliced grid. _delta must account for rotation to give correct user coordinates.
> 
> I've started going down this path with the RegularGrid by adding the rotation parameters. I'm giving them default so previous instantiations of RegularGrid should continue working. But there are 10 functions in the RegularGrid class that utilize _delta, and I'm concerned about regressions.
> 

I'm not sure I'm following this. Can you construct a case that demonstrates them problem, or point to the offending code?

> **Option 3** Another option is to create an UnstructuredGrid2D with explicitly defined grid points. The constructor is a bit of a beast so I'm shying away from this route until I can get some advice.

No, this is not what we want to do. Let's see what is involved in addressing option 2.

**Comment by sgpearse** [comment]
> I'm not sure I'm following this. Can you construct a case that demonstrates them problem, or point to the offending code?

I can try.  I'll prep for a live demo at tomorrow's meeting, or sooner if you'd like to talk beforehand.  This is hard to explain without a visual.

1) Check out the branch 2DgridDemo
2) Load any dataset and create a slice renderer rotated by +90 on the X axis.  Enable it.

The 2D grid that is created is of size [ sideSize x sideSize x 1 ] on XYZ.  This is done at SliceGridAlongPlane.cpp:251.  The normal of this slice is pointing along the negative Y axis.

At SliceGridAlongPlane.cpp:258, I am printing the user coordinates of this slice at XYZ indices 000 and 010.  This is done with RegularGrid::GetUserCoordinates.

When the Y index is changed between these two queries, the Z coordinate is unchanged.  Incrementing the Y index needs to increase our Z user coordinate due to the grid's rotation.  But the RegularGrid has no notion of the rotation, so it currently cannot calculate the grid cell coordinates.

**Comment by clyne** [comment]
OK. I wasn't thinking. The RegularGrid has to be axis-aligned. The X, Y, and Z coordinates can only be described as a function of a single variable, which is not general enough to describe an arbitrary plane. Think about it; the RegularGrid constructor only accepts a min and max extents to describe ALL of the coordinates. That's not sufficient to define a plane of any orientation. To describe an arbitrarily oriented plane each X,Y,Z coordinate must be a function of 3 logical variables (e.g. X(i,j,k), Y(i,j,k), Z(i,j,k)). The Unstructued2DGrid has the flexibility to do this, but it's definitely never been tested. If we want to contain the plane in a Grid class,  I think we are back to storing it as a 2D, axis-aligned object and there will need to be a transformation between 3D and 2D coordinates to use it. @stasj you were the one that suggested using the Grid class. Am I missing something?

**Comment by clyne** [comment]
On thought, and maybe this is what @StasJ had in mind all along: Derive a "SliceGrid" from the regular grid that performs the forward (and inverse if needed) projection from 3D to 2D. Only a couple of RegularGrid methods would need to be derived. N.B. if the coordinate iterators are used this will be a possibly much bigger lift.
