### ISSUE TITLE
Flow fidelity inconsistent results

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#2978]
1. Open `Bugs/2935/MFR/mydata.vdc`
2. Create/enable a flow renderer with the `bx`, `by`, `bz` vars
3. Change the fidelity

Notice that as you change the fidelity the resulting paths are very inconsistent. If you render the `bx`, `by`, `bz` directly, you can see that they remain mostly unchanged among fidelity levels. Pictures of both are below.

### Flow High
<img width="585" alt="flow_high" src="https://user-images.githubusercontent.com/2772687/150864562-b1725b0b-06fa-4f04-ab0d-8ccced9f1418.png">

### Flow Med
<img width="585" alt="flow_med" src="https://user-images.githubusercontent.com/2772687/150864570-d25e34fa-1db6-450e-a23e-5cfc341e59f3.png">

### Flow Low
<img width="585" alt="flow_low" src="https://user-images.githubusercontent.com/2772687/150864573-adf18490-a20b-4c02-a9fa-caaf86e459f0.png">

### `by` High
<img width="585" alt="slice_high" src="https://user-images.githubusercontent.com/2772687/150864706-b8c46900-7a31-49f6-a253-36bb66cacb59.png">

### `by` Med
<img width="584" alt="slice_med" src="https://user-images.githubusercontent.com/2772687/150864714-2583f692-2147-444b-8f95-8ac3ec78a3f6.png">

### `by` Low
<img width="585" alt="slice_low" src="https://user-images.githubusercontent.com/2772687/150864717-25c08ed0-44b9-456c-9444-c754af6cc9ad.png">

**Comment by shaomeng** [comment]
I investigated this data set, but didn't find anything wrong with the flow renderer. 

One thing I did notice is that this data set has mostly very-close-to-zero values in the volume, so that in the "high" fidelity rendering, many seeds proceeded very little distance. On the contrary, they traveled more distance in the "low" fidelity rendering, which could be explained by farther-from-zero values lossy compression introduced.

I tend to think this is a normal behavior than a bug.

**Comment by clyne** [comment]
@shaomeng how is the initial integration step size computed, and is its calculation based on the cell size, which will change with with different resolution levels in a VDC data set? If the integration step size varies with different levels in the multi-resolution data representation, are you adjusting the limits of integration (number of integration steps) to account for this? If not, I think that would explain the variation in stream line length that @stas is observing.

**Comment by shaomeng** [comment]
It turns out, for structured grids which is the case in this data set, the initial step size is determined as the following: 

the initial step size is chosen so that it would take two times of the number of cells to travel through the diagonal of the volume. 

(The initial step size for unstructured grids is determined so that it'd take 1000 steps to travel through the volume.)

With this particular data set, the High and Low fidelity settings have a two orders of magnitude difference in dimension, so initial step sizes would differ by approximately two orders of magnitude too. I think this difference also explains the visually different results.

**Comment by clyne** [comment]
What do you mean by " two orders of magnitude difference in dimension"?

**Comment by shaomeng** [comment]
> What do you mean by " two orders of magnitude difference in dimension"?

With High fidelity, the number of cells along the diagonal is in the order of thousands, and with Low fidelity, it's in the order of dozens. This difference is roughly two orders of magnitude.

**Comment by clyne** [comment]
For multiresolution data can't you simply scale the limits of integration accordingly so that the length of the field lines when toggling between different resolutions doesn't change so much?

**Comment by shaomeng** [comment]
> For multiresolution data can't you simply scale the limits of integration accordingly so that the length of the field lines when toggling between different resolutions doesn't change so much?

I assume by "limits of integration" you meant the number of steps? If the number of steps is adjusted, then the user would easily notice that their input is not honored. Worse, when the user writes the field lines to a file, the discrepancy is even more obvious. 

I think it's desirable to produce closely matching visualizations when fidelity is changed, however in this case, one might just have to accept that they need some tweaks to make them look alike. This is a less bad behavior than bluntly not honoring the user input number of steps.

**Comment by clyne** [comment]
> > For multiresolution data can't you simply scale the limits of integration accordingly so that the length of the field lines when toggling between different resolutions doesn't change so much?
> 
> I assume by "limits of integration" you meant the number of steps?
Yes


> If the number of steps is adjusted, then the user would easily notice that their input is not honored. Worse, when the user writes the field lines to a file, the discrepancy is even more obvious.
> 
> I think it's desirable to produce closely matching visualizations when fidelity is changed, however in this case, one might just have to accept that they need some tweaks to make them look alike. This is a less bad behavior than bluntly not honoring the user input number of steps.

Then please propose some other solution to this problem. Three different VAPOR developers have already been confused by this behavior. You even originally postulated that there was something unusual about the the data, before ultimately digging into the code to try to explain what we are seeing. If the developers are confused by the behavior, how do you expect users not familiar with the algorithm to react?

**Comment by clyne** [comment]
Re documentation: one of the goals we've always striven for with the GUI is to minimize the need to consult the documentation, because as we all know it is better for things to behave intuitively than to expect users to RTFM. In this case, I'm not sure "causing user input to be violated" is really an issue, because without knowing the integration step size the number of integration steps has no physical meaning; it simply controls how long the stream/path lines.

But if this is really a concern to you, how about simply scaling the integration step size appropriately when the data are coarsened? The step size is not a parameter that we expose, so we would not be violating user inputs.

**Comment by shaomeng** [comment]
> But if this is really a concern to you, how about simply scaling the integration step size appropriately when the data are coarsened? The step size is not a parameter that we expose, so we would not be violating user inputs.


Sure. Is there a member function from the grid class to know the following 2 pieces of information, ideally without reconstructing the full-resolution grid? 
1) the current grid is indeed a coarsened version of another grid? 
2) the full resolution of the other grid?

**Comment by clyne** [comment]
The method you want is on the DataMgr:

`DataMgr::GetDimLensAtLevel(string varname, int level, std::vector<size_t> &dims_at_level, long ts)`

**Comment by shaomeng** [comment]
> The method you want is on the DataMgr:
> 
> `DataMgr::GetDimLensAtLevel(string varname, int level, std::vector<size_t> &dims_at_level, long ts)`

Thanks for the pointer. Now this change is made in #3172
