### ISSUE TITLE
WRF-Fire extents being misinterprited

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3056]
To reproduce:
1) Import [this WRF-Fire file](https://drive.google.com/file/d/1HZXeWLyHCmd9L537TFRb3gJl1EpZXFEY/view?usp=sharing)
2) Enable axis annotations.  Vapor reads the extents as follows:
    Latitude range: 39.98 to **66.40**
    Longitude range: -106.348 to -**18.6**

Run ncdump -v XLAT to see the latitude range as
    39.98 to **40.44**

Run ncdump -v XLONG to see the latitude range as
    -106.348 to **-105.5497**

**Comment by sgpearse** [comment]
Followup:

> Near the boundaries, WRF-Fire sets the values to something non-physical. It looks like for this case, the values are 0, but for the Marshall files, the values are NaN. Maybe this is the problem?

**Comment by clyne** [comment]
This problem is occurring because the attached WRF-SFIRE output contains variables that are dimensioned by 'south_north_subgrid' and 'west_east_subgrid'. To the best of my knowledge these dimensions do not exist in vanilla WRF, and were introduced in the SFIRE fork of WRF. Perhaps @janmendel can comment?

WRF does not follow the Climate Forecast conventions; the association between a data variable and coordinate variables is hard-coded (though later versions of WRF have adopted some CF attributes such as 'coordinates', which might be used to make this association. 

Note, another difference between this model output and vanilla WRF is the presence of an 'XTIME' variable that is presumably intended to be the time coordinate (vanilla WRF uses a variable named 'Times').

**Comment by clyne** [comment]
Never mind earlier comments. The problem with this data set is that it defines a non-conforming grid; the last lat-lon coordinate pairs for FXLONG and FXLAT are all zero.
