### ISSUE TITLE
conda installation doesn't work in extant conda envionments

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3118]
The conda installation for VAPOR-Python (`install_vapor.sh`) will exit if the conda environment has existing packages in it. This limits the use of the package (or at least complicates the use) if VAPOR-Python can't be used with other Python packages that aren't included with the installer.

**Comment by StasJ** [comment]
This is intentional. If you ran the installer in an existing environment without that check, it would most likely fail to resolve the dependencies due to prior locked requirements. If it succeeded, it would end up reinstalling 90% of the environment anyway. Vapor-Python can still be used with other python packages, you just install them after running the installer. In any event, install_vapor.sh is just a utility program to simplify installing the python API before it is officially released.

**Comment by clyne** [comment]
Thoughts on this @kmpaul?
