### ISSUE TITLE
Transforms: Renderer transform origin should be centered w.r.t. current variable

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#316]
I believe that when we apply transforms to individual renderers, the origin should be the center of that variable's extents.

To reproduce:
1) Spin up Vapor, load KatrinaMaster.nc
2) Create a 2D renderer and enable it
3) In the Geometry tab, scale the renderer by 2.  The rendering is no longer centered within the domain

**Comment by clyne** [comment]
Stas, I looked over the code and I think setting a more reasonable default origin for the transforms is pretty straight forward for both the renderer transform (on the Render/Geometry subtab), and the data set transform (Navigation/Viewpoint) tab.

For the renderer transform you just need to set the origin on the _transform member inside the RenderParams constructor. Note: the RenderParams constructor is overloaded and only the one with the signature: 

RenderParams::RenderParams(
    DataMgr *dataMgr, ParamsBase::StateSave *ssave, const string &classname,
    int maxdim
);

should be changed. You can simply use the _Box class to find the center of the domain

For the dataset transform it's a little more tricky. Your best bet may be to modify the ViewpointEventRouter::updateTransforms() method so that the first time it sees a new transform (dataset name) it sets the origin of the transform returned by vParams->GetTransform(names[j]) The tricky part is picking a good value. The DataStatus class has a method:

DataStatus::GetActiveExtents() that returns the union of the extents of all of the "active" variables. However, the current version does this for ALL data sets. You would need to implement an overloaded version that allows the specification of a particular data set.

This should work! Let me know if you have questions.
