### ISSUE TITLE
VAPOR 3.7 crashes on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by winash12** [NCAR/VAPOR#3280]
### Describe the bug

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ x] Did VAPOR crash?
Cannot mix incompatible Qt library (version 0x50c08) with this library (version 0x50d02)

Does VAPOR look for another location for Qt on Ubuntu 20.04 LTS ? 
- [ ] Did you get wrong results?

**Impact**
- [ ] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:

*Additionally, please attach a session file to this ticket to easily reproduce (use File->Save Session).*

### Attachments
* Can you reproduce the bug on our test data?
  * If so, which file?
  * If not, access to your data would be very helpful. If the data set is small, please zip and upload it as an attachment. If it is large, please provide instructions for how we can contact you to obtain this data.
* Please attach a session file to easily reproduce (use File->Save Session).
* Please attach any screenshots relevant to understanding the issue.

### Desktop
 - OS and version: [e.g. Ubuntu 18.04]
 - Version: [e.g. Vapor 3.1]

### Additional context
Add any other context about the problem here. Attach any (zipped) relevant files, such as data, configurations, session files, etc.

**Comment by sgpearse** [comment]
@shaomeng Vapor is crashing on startup on Ubunt 20 and 22 on startup due to our installer not including Qt5DBus.so.

CMake is not linking Vapor to this library for reasons I do not know.  Our installer build system runs ldd on our binaries to see what libraries to bundle, and since vaporgui isn't linking to DBus, we don't bundle it.  We explicitly link DBus in vaporgui's CMakeLists.txt using target_link_libraries(), and CMake does successfully link on all other platofrorms.

This slipped past the platform tests because the test machines were used for the 3rd party library update.  While /usr/local/bin/VAPOR-Deps/2019-Aug was moved/deleted on these machines, they had Qt installed.  Vapor was finding DBus from those Qt installations.  We used to have dedicated test systems, but not dedicated development systems for each platform.  After this, it's probably worth having both.

Why vapor is not linking to DBus is still unknown to me.  The issue arose after the Python API branch got merged, however I cannot find anything in that commit that should be affecting vapor's linkage.  I've tried backing out CMake to versions going back to 3.17 (used in Vapor 3.6) but the problem persists.

**Comment by winash12** [comment]
@shaomeng It is very easy to reproduce my error. All you need is a Ubuntu 20.04 LTS box and try installing VAPOR 3.7 on that box and voila you will see the same error message that I have shown 
`Cannot mix incompatible Qt library (version 0x50c08) with this library (version 0x50d02)`

**Comment by shaomeng** [comment]
Thanks for your input. We'll look into it! @winash12

**Comment by sgpearse** [comment]
@winash - I believe I have a fix. Could you please try [this installer](https://output.circle-artifacts.com/output/job/14e5d12c-e3c3-4880-bfd3-0245d53988c2/artifacts/0/tmp/workspace/installers/VAPOR3-3.7.1-Ubuntu18.sh) and let us know if it works for you?

**Comment by winash12** [comment]
@sgpearse I am not able to download that link ? It gives me a blank page.

**Comment by winash12** [comment]
@sgpearse Yes that fixed it. I am able to go to the bin directory and trype ./vapor and I am able to see the GUI. We could go ahead and close this issue and open news ones as and when they arise.

**Comment by sgpearse** [comment]
@winahs Thank you for reporting this and for checking.  We will close it once PR #3283 has been merged, so I'm re-opening it for now.

**Comment by ogressel** [comment]
> @winash - I believe I have a fix. Could you please try [this installer](https://output.circle-artifacts.com/output/job/14e5d12c-e3c3-4880-bfd3-0245d53988c2/artifacts/0/tmp/workspace/installers/VAPOR3-3.7.1-Ubuntu18.sh) and let us know if it works for you?
this installer worked for me on Ubuntu 20.04 LTS -- kudos for the fast response!
