### ISSUE TITLE
Flow First Step Size Multiplier impacts overall step size

### ISSUE THREAD

**Issue by StasJ** [NCAR/VAPOR#3360]
1. Follow instructions in #3318
2. Adjust First Step Size Multiplier

Notice the final trajectory length varies as you change the First Step Size Multiplier. Below are examples with different First Step Size Multiplier values:

### 1E-4
![1E-4](https://user-images.githubusercontent.com/2772687/227071725-9ba3069c-adf3-4575-8beb-41d49c7d5421.png)
### 1E-3
![1E-3](https://user-images.githubusercontent.com/2772687/227071729-b78ae6bc-8e11-4b76-9278-ef0297bf66c4.png)
### 1E-2
![1E-2](https://user-images.githubusercontent.com/2772687/227071732-4aed5a57-95bd-4eb5-aeea-9b8be7baaa00.png)
### 1E-1
![1E-1](https://user-images.githubusercontent.com/2772687/227071734-c6008ec3-6dd4-4594-96e2-87176cf619a8.png)
### 2E-1
![2E-1](https://user-images.githubusercontent.com/2772687/227071735-74cead26-bd51-4690-839b-5464bfdae244.png)

**Comment by shaomeng** [comment]
Hmm, I would not consider this a bug. Let me clarify.

A less obvious fact about flow line integration is, there isn't an absolutely true flow line that renders all others false. The step size in use definitely has an impact on the shape and/or length of the output flow line, they *can* all be correct step sizes, though different.

Ideally, the flow integration step size results the particle being advected travel exactly one grid cell a step. If a particle travels more than one grid cell a step, it skips grids, which is usually considered wrong. If a particle travels multiple steps in one grid cell, one doesn't gain more information/accuracy inside of the same grid cell;  it's considered less than ideal because unnecessary computation is performed, but it's not considered wrong. In fact, the flow code automatically adjusts the step size of every integration operation trying to be close to the ideal situation.

As far as the observation reported here, it's just a natural result of different step sizes. They can be and do appear to be correct at the same time.
