### ISSUE TITLE
Flow trajectory internal time step not constant or selectable by user

### ISSUE THREAD

**Issue by leighorf** [NCAR/VAPOR#3373]
### Describe the bug
When saving pathlines to a text file, the time step used by Vapor is not constant, and the number of sub-timesteps Vapor chooses to use to do time integrations is not selectable by the user, and Vapor could be choosing a much smaller time step than necessary to do pathlines, wasting cycles.

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ ] Did VAPOR crash?
- [x] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Create pathlines, save them to a file, and look at the results.

### Expected behavior
The time step used by VAPOR should be constant, such that the sequential times in the VaporFlow.txt should be separated by a constant dt, not one that has "jitter".

Furthermore, it is unclear how Vapor determines its internal time step for integrating particle/pathline locations. It is subdividing my own data's time step by a factor of 4 unnecessarily (stability would be easily found with my current 0.2 second spaced netcdf files).

### Desktop
 - OS and version: [e.g. Ubuntu 18.04]
 - Version: [e.g. Vapor 3.1]

### Additional context
Here is what I am talking about, notice the bolded column, the 'Raw-time' field. Why is time not advancing at exactly 0.05 seconds? And why did it choose that particular time step to integrate?

ID,  X-position,  Y-position,  Z-position,  Formatted-time, Raw-time,  uinterp,  vinterp,  vortmag,  windmag_sr,  winterp
0, -6.499170, 5.392221, 0.266415, 2001-01-01_01:29:18, **5358.000000**, 66.998596, -31.042908, 0.190460, 81.897400, 35.417053
0, -6.495925, 5.390718, 0.268126, 2001-01-01_01:29:18, **5358.048444**, 66.970802, -31.016191, 0.190013, 81.776497, 35.212711
0, -6.492713, 5.389375, 0.269809, 2001-01-01_01:29:18, **5358.096888**, 65.628708, -24.404797, 0.071494, 77.947952, 34.250847
0, -6.488682, 5.388030, 0.271972, 2001-01-01_01:29:18, **5358.157442**, 70.202835, -18.848616, 0.071707, 81.002106, 35.740322
0, -6.485695, 5.387229, 0.273488, 2001-01-01_01:29:18, **5358.200000**, 70.194061, -18.787415, 0.073820, 80.870132, 35.492828
0, -6.482709, 5.386430, 0.274995, 2001-01-01_01:29:18, 5358.242558, 70.115952, -18.761202, 0.077183, 80.710449, 35.297512
0, -6.478949, 5.385475, 0.276863, 2001-01-01_01:29:18, 5358.295755, 73.788620, -13.910225, 0.131567, 82.710953, 34.687641
0, -6.474044, 5.384551, 0.279157, 2001-01-01_01:29:18, 5358.362251, 73.717674, -13.881069, 0.131617, 82.490372, 34.322823
0, -6.471262, 5.384040, 0.280461, 2001-01-01_01:29:18, 5358.400000, 73.820145, -11.775009, 0.103210, 82.984863, 36.037308
0, -6.467664, 5.383727, 0.282142, 2001-01-01_01:29:18, 5358.447186, 76.680969, -5.616015, 0.134536, 84.662659, 35.451656
0, -6.464048, 5.383462, 0.283809, 2001-01-01_01:29:18, 5358.494371, 76.591019, -5.605550, 0.135282, 84.471573, 35.189396
0, -6.459515, 5.383200, 0.285869, 2001-01-01_01:29:18, 5358.553353, 78.439369, 1.376345, 0.148214, 85.604874, 34.271145
0, -6.455857, 5.383264, 0.287461, 2001-01-01_01:29:18, 5358.600000, 78.391479, 1.365814, 0.148104, 85.448517, 33.997604

**Comment by shaomeng** [comment]
Hi @leighorf , I think the behavior of VAPOR's `dt` choice could use some discussion and hopefully arrive at a better solution. I'm going to explain the current behavior so that we'll be on the same page to consider improvements.

VAPOR currently pre-determines an initial `dt` to get the integration started, and then adjust `dt` at every subsequent step.
The initial `dt` is determined so that a particle needs 2X steps of the domain dimensions to travel the entire domain. The `dt` adjusting scheme is based on the curvature of the past 3 steps: 
- if the angle  is below 3 degrees, so it's quite flat, then `dt` is scaled up by 1.25.
- if the angle is bigger than 15 degrees, so it's a little sharp turn, then `dt' is halved.
- there's no change to `dt` in the rest cases. 

So I think maybe there can be 2 improvements to achieve what you described:
1) Provide a user-input option to dictate the initial `dt`, rather than using VAPOR's calculation.
2) Provide a checkbox to disable the dynamic adjusting. 

What do you think of these 2 possible improvements? Is there a better idea of achieving what you need?

**Comment by leighorf** [comment]
Sam, I would be very happy with those solutions. With the dynamic adjusting turned off, I presume the user would be required to supply the time step (that would be my wish). Letting users choose these would be great as many users will already have a very good feel for what dt to use.

**Comment by leighorf** [comment]
Another thought comes to mind. If we use a constant dt across all particles for all times, might there be a way to optimize the calculations of trajectory locations better? I would guess that calculating a dynamic dt for each parcel for each time step has a lot of overhead (and I don't think it currently is multithreaded).

**Comment by shaomeng** [comment]
> Sam, I would be very happy with those solutions. With the dynamic adjusting turned off, I presume the user would be required to supply the time step (that would be my wish). Letting users choose these would be great as many users will already have a very good feel for what dt to use.

I think this is doable. I'd imagine that a user input is treated as an "advanced" option, and as soon as a user opts for manually input a time step, all "smart" program logics (initial steps, dynamic adjustments) are disabled. I can make this improvement. I'll see if other team members (@NihanthCW @sgpearse @StasJ) have concerns.

**Comment by shaomeng** [comment]
> Another thought comes to mind. If we use a constant dt across all particles for all times, might there be a way to optimize the calculations of trajectory locations better? I would guess that calculating a dynamic dt for each parcel for each time step has a lot of overhead (and I don't think it currently is multithreaded).

I think using a fixed dt (user provided) can definitely improve performance, but it won't be a dramatic one, because the calculation of the curvature of last 3 particles is pretty cheap. In my experience, retrieving values from a random grid location (as required by RK4) is the most expensive.

With that been said, I think providing a fixed `dt` can be the first step of improvement, and we can profile its performance again to identify hotspots and improve its performance.

**Comment by sgpearse** [comment]
Fixed with #3505
