### ISSUE TITLE
Image cannot be moved to the bottom of the domain

### ISSUE THREAD

**Issue by AvijeetPrasad** [NCAR/VAPOR#3383]
### Describe the bug
- Load magnetic field values bx, by, bz at full refinement. 
- Load an image. Now the level of refinement for the image is stuck at 0
This means that the image cannot be pulled down to the bottom of the domain.

**Impact**
- [ ] High - User productivity significantly degraded
This seriously affects the quality of the images that we can generate.

### Expected behavior
The image plane should be able to move to the bottom of the domain.

### Attachments
My dataset is large, so I am just zipping the session file.
[vapor_session.vs3.zip](https://github.com/NCAR/VAPOR/files/11287484/vapor_session.vs3.zip)

Below I am showing the settings available for image, and you can see that we cannot change the refinement level. I guess that's okay, as long as we can move the image plane.

<img width="415" alt="Screenshot 2023-04-20 at 16 49 42" src="https://user-images.githubusercontent.com/45669486/233404465-ec83675d-20d1-4318-9bfc-a791eeb8e8a0.png">

I am showing the issue below. The yellow plane is the image I am trying to load. I want it to coincide with the bottom plane, where I have a slice. But I am not able to move it down and you can see about 4 pixels of space between the two planes.

<img width="1841" alt="Screenshot 2023-04-20 at 16 44 34" src="https://user-images.githubusercontent.com/45669486/233402534-44adccf3-2faa-4217-85ad-64d7b006ed6b.png">

### Desktop

 - OS and version: MacOS 13.3.1 Intel
 - Version: Vapor 3.8.1

### Additional context
This issue was not there in the previous versions as far as I can remember.

**Comment by sgpearse** [comment]
This could potentially be related to #3277.  Could you provide us with a sample of your data so we can reproduce and fix it?  As a workaround, you can adjust the z coordinate of the image in the Geometry tab under the Transform->Translate option.

![Screen Shot 2023-04-20 at 9 55 30 AM](https://user-images.githubusercontent.com/9522770/233421167-e8a8b81d-28b4-4f18-986e-2fdbffce8dec.png)

**Comment by AvijeetPrasad** [comment]
Hi Scott, 
Thanks for looking into this. I am attaching a Dropbox link to a zip file containing the Vapor data, vdc and vs3 files, so that you can reproduce the bug. Let me know if you have any issues in accessing the file.

https://www.dropbox.com/s/1ze1ybk0hfh03pj/Vapor_Bug_Report.zip?dl=0

**Comment by sgpearse** [comment]
Possibly related to #3575 and #3574

**Comment by sgpearse** [comment]
This issue still persists.  But I think the reasonable workaround is to translate the Image renderer in the Geometry tab.

![Screen Shot 2024-11-15 at 9 41 02 AM](https://github.com/user-attachments/assets/90d49af6-4730-45ac-8fd0-83195abe9865)

The problem is that this is a VDC dataset that has no 2D variables to derive the domain's extents from.  VAPOR is defaulting to the coarsest resolution grid of the VDC, which has a higher minimum Z extent than the maximum refinement grid.  Since this is somewhat of an edge case (VDC+No 2D vars) I'm going to leave this closed for now.  @AvijeetPrasad thank you for reporting this and let me know if you have any questions or other issues.
