### ISSUE TITLE
UnstructuredGrid2D broken

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#3566]
To reproduce:

1) import /glade/p/cisl/vast/vapor/data/Source/MPAS/FalkoJudt/*

Vapor will crash.  This is also causing our smoke tests to fail.

**Comment by NihanthCW** [comment]
@StasJ will investigate and reassign to Sam if needed.

**Comment by sgpearse** [comment]
Note: The [fix_ptr_cache PR broke the smoke tests](https://app.circleci.com/pipelines/github/NCAR/VAPOR/7337/workflows/bfbe5f2a-96f9-4348-aae5-7e8adcf23e10/jobs/18260) for the same reasons in UnstructuredGrid2D.

**Comment by shaomeng** [comment]
The crash is because of the failure of this assertion:
https://github.com/NCAR/VAPOR/blob/d25aaf05637d960f8ca942879627bfc427dccd47/lib/vdc/UnstructuredGrid.cpp#L29
where the vertex dims are reported to be 2, and edge dims are reported to be 1. 

I think this disagreement between queried dimensions really needs some intervention from @StasJ .
