### ISSUE TITLE
VAPOR can't read the WRF outputs from the CONUS404 reanalysis data set

### ISSUE THREAD

**Issue by clyne** [NCAR/VAPOR#3588]
VAPOR is unable to read the CONUS404 data set hosted on the RDA [repository](url). The outputs are a reanalysis product, written in WRF format. When trying to import any of the files in the collection VAPOR complains about the XLONG variable

**Comment by NihanthCW** [comment]
Bumping up this issue. We have another collaborator who is running into the same issue .

**Comment by NihanthCW** [comment]
[RDA repo link](https://rda.ucar.edu/datasets/ds559.0/)

**Comment by shaomeng** [comment]
The file fails to be imported because there's a check inside VAPOR: if the two variables "XLONG" and "XLAT" are 3 dimensions:
https://github.com/NCAR/VAPOR/blob/f603609f185f2296c0c27fefc77985fd2a25a327/lib/vdc/DCWRF.cpp#L988-L993

This particular dataset, however, is having both variables as 2 dimensional: 
![Screenshot from 2024-05-31 13-14-32](https://github.com/NCAR/VAPOR/assets/814885/e40c207b-f356-48c0-ba77-48ca2d72449f)

@clyne what do you think this situation should be handled?

**Comment by clyne** [comment]
@shaomeng unfortunately there is no specification for WRF output files; they don't follow anything like the CF conventions. So all of the code used to read WRF outputs was developed in response to sample data sets. All of the previous files VAPOR has been tested on have had horizontal coordinate variables that are time varying. The CONUS404 data, which are reanalysis products, apparently do not. The good news is that not having time varying coordinates is definitely a simpler case to handle than having time varying coordinates. The code have to be generalized to not require a time dimension for the horizontal coordinate variable. This shouldn't be too difficult, and as a starting point I would suggest simply the requirement:

`latlondims.size() != 3`

and see what happens :-)

**Comment by shaomeng** [comment]
@clyne Good suggestion. After removing the dimension equals 3 test, the data set imports and renders well. However, it's a little unclear if something else got broken...
