### ISSUE TITLE
What happens to an existing session when I create a new session?

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#38]
It's not clear to me what happens to my working session if I chose to create a new session from the File menu.

**Comment by shaomeng** [comment]
We should warn users that the old session is going to be gone.

**Comment by shaomeng** [comment]
@StasJ I'm working on this issue to add a pop up box to warn users. I remember you implemented an awesome warning/error message mechanism. How to use that?

**Comment by sgpearse** [comment]
The warning popup appears when we load a new session from the command line (ie >vaporgui /path/to/mySession.vs3 results in a warning that we're about to lose a session).  

I'd like to suggest the following:
1)  Avoid the warning in this situation since the previous session is in a blank state and there's nothing to lose.
2) Allow the user to perform a "Save session as" operation from the warning menu, so that they could either proceed, cancel, or proceed+save.
3) Change the word "lose" to "lost" in the popup.

**Comment by shaomeng** [comment]
hmm, the current warning message isn't intelligent enough to distinguish this case, so it pops up more often than necessary.

To eliminate these unnecessary pop-ups, we'll need to plant a flag in the ParamsMgr class to keep track of any changes, and it's a fair amount of work. 

Let's discuss if we want to pursue that direction.

**Comment by shaomeng** [comment]
It seems VAPOR is intelligent enough to pop up warning messages only when settings are changed. I'm going to close it unless new misbehaviors are found.
