### ISSUE TITLE
No installed transfer functions

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#399]
Our pre-installed transfer functions are being omitted with our current installer.

To reproduce:
1) Open any dataset, create any renderer
2) Load a transfer function.  None of our native files are present.

**Comment by sgpearse** [comment]
Need to add extra map TIFF files

**Comment by clyne** [comment]
This problem still exists on the Mac. Not sure about other platforms.

**Comment by StasJ** [comment]
@clyne How are you encountering this bug? I just did the following:

1. Install vapor.app
2. Open Katrina
3. Create TwoDData renderer
4. Click `Appearance` -> `Load TF`

A file selection window is then opened pointing to `/Applications/vapor.app/Contents/share/palettes/` and all of the `.tf3` files are there.

**Comment by clyne** [comment]
When I perform these steps the finder window points to the top-level Applications directory. Possibly because I have vapor 2.6 installed, or because I’m running Mac OS X 10.12?

Anyway, we need to focus on completing our testing spreadsheets now and will prioritize bugs later.

thanks - jc

> On Nov 27, 2017, at 1:38 PM, StasJ <notifications@github.com> wrote:
> 
> @clyne How are you encountering this bug? I just did the following:
> 
> 	• Install vapor.app
> 	• Open Katrina
> 	• Create TwoDData renderer
> 	• Click Appearance -> Load TF
> A file selection window is then opened pointing to /Applications/vapor.app/Contents/share/palettes/ and all of the .tf3 files are there.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu
