### ISSUE TITLE
OSX Binary: Bundled color palettes not accessible

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#473]
I don't seem to be able to load Vapor's .tf3 files.

To reproduce:
1) Spin up Vapor with KatrinaMaster.nc
2) Create a new TwoDData renderer
3) In the Appearance tab, load a transfer function.  The file browser dialog directs me to my Applications folder, where I'm not able to access the vapor.app directory that contains our contents.

**Comment by clyne** [comment]
The issue here is that the path to the palettes directory is a startup parameter. By default it points to the palettes repository within the vapor installation. However, the user can change the default location and save it to the startup file, ~/.vapor3_startup. The default can be restored by clicking Settings/Startup/Restore Defaults.
