### ISSUE TITLE
Contours: Discontinuity with increasing Refinement Level

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VAPOR#778]
There seems to be a discontinuity in our contours along the diagonal that spans from xMin,yMin to xMax,yMax.  This becomes more pronounced as the Refinement level increases.  See screenshot below.

To reproduce:
1) Load Katrina
2) Create a new contour renderer with variable T2 at maximum fidelity and enable it
3) Make the Contour Count = 50, decrease the Spacing so all contours fit
4) Reduce the refinement to 0, and it goes away

<img width="1023" alt="screen shot 2018-05-03 at 9 12 42 am" src="https://user-images.githubusercontent.com/9522770/39585512-3d2ad83e-4eb2-11e8-9069-3eb42b9b826b.png">

**Comment by StasJ** [comment]
The contour renderer is getting an invalid grid from the data manager. The grey lines are the grid cells:

![screen shot 2018-05-03 at 2 28 21 pm](https://user-images.githubusercontent.com/2772687/39601161-4e4bd2cc-4ede-11e8-8bb6-e891771f9cd1.png)

![screen shot 2018-05-03 at 2 28 28 pm](https://user-images.githubusercontent.com/2772687/39601168-521aea3c-4ede-11e8-8db2-10d507e9fb03.png)

**Comment by StasJ** [comment]
This is occurring because of grid->ConstCellBegin(boxMin, boxMax). The 2D renderer does not use this function and instead takes care of the extents itself. I found that Grid::InsideBox is returning certain cells are outside the extents even though all cells should be inside. I think you should take a look at this @clyne
