### ISSUE TITLE
Geometry Tab initialize to be at the middle, instead of the max range

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#917]
To reproduce: 
1. Open VAPOR, load VDC data:
`/little_glade/shaomeng/synthetic/four/four.nc`.
2. Create a "Wireframe" renderer, click on the right-most fidelity control, enable the renderer. 
3. Notice nothing gets rendered.
4. Go to the "Geometry" tab. Notice the X, Y, Z coordinates are all at position `1.5`. 
5. Change the X, Y, Z coordinates to cover the entire volume, then a wireframe gets rendered. 

Note: the test data is a cube with 4x4x4 grid points.

**Comment by shaomeng** [comment]
Note, the Min/Max slider of the TF widget initializes to be at the middle, instead of the max range, as well. I believe that one shares the same cause of this one.

**Comment by sgpearse** [comment]
I think there is more at work here than the TFWidget.  It's just requesting the range of the variable through DataMgr::GetDataRange() at line 217 of TFWidget.cpp; for which it's receiving a minimum and maximum variable value of 1.63261.

I'd like to get John's opinion on where to go with this one because I think the problem is with the DataMgr or with the data set.  I can keep helping if it's either one.

**Comment by shaomeng** [comment]
Update on 12/20: This is still the case. Also, it's severity needs to be determined, so I'm taking off the `low` label.

**Comment by shaomeng** [comment]
Not longer applicable.
