### ISSUE TITLE
TFWidget crashes

### ISSUE THREAD

**Issue by shaomeng** [NCAR/VAPOR#930]
To reproduce:
1. Use the latest `master` branch code, compile with `Release` option.
2. Open VAPOR, load data `/little_glade/shaomeng/synthetic/sphere/sphere1024.nc`.
3. Create a `wireframe` renderer.
4. Change `Fidelity` option to the right-most radio button.
5. VAPOR crashes with a failed assertion in TFWidget.

Note, the `/little_glade/shaomeng/synthetic/sphere/sphere1024.nc` data was created using the following commands on cisl-vapor:
- `/home/shaomeng/Build/VAPOR-new-DVR-build/bin/vdccreate -bs 256:256:256 -cratios 10:1 -dimension 1024x1024x1024 -vars3d gaussian -wname bior4.4 sphere1024.nc`
- `/home/shaomeng/Build/VAPOR-new-DVR-build/bin/raw2vdc -varname gaussian -debug sphere1024.nc sphere1024.float`

**Comment by sgpearse** [comment]
It turns out that the assertion is being caused by the DataMgr returning a bad RC after not being able to perform GetDataRange().

After digging deeper, the DataMgr is not able to retrieve the Grid object for the target variable at level=-1 and lod=-1, which correspond to the least compressed data representation.

If you use the 'Level of Detail' and 'Refinement Level' combo boxes, you can access the least compressed data representation.  It's the -1, -1 values of the Fidelity controller that cause this.  I'm going to bring John into this to see how he wants to handle it.
